### ISSUE TITLE
Is this up-to-date?

### ISSUE THREAD

**Issue by TranzRail** [nicoco007/AuraSDK#1]
Hi there,

Interested in using your wrapper, would like to know if it's still maintained?

For reference, system is a ASUS X99 Deluxe-II with 8 DIMMS of TridentZ RGB memory.
 
Cheers

**Comment by nicoco007** [comment]
Sorry for taking so long to reply! Yes, I'm still maintaining it, but since Asus hasn't updated their stuff in a while I haven't been doing much with it. Note also that RAM isn't supported by their SDK and therefore not supported by this; I'm trying things out on my end but haven't gotten very far.
